name: CI

on:
  push:
  pull_request:

jobs:
  install:
    strategy:
        matrix:
          platform: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.platform }}  
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Run the installer
        run: |
          bash install.sh nightly all
          bash install.sh stable all
          bash install.sh epoch cli
