name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install:
    strategy:
        matrix:
          platform: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.platform }}  
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with:
          distribution: oracle
          java-version: 17
      - name: Print diagnostics
        run: |
          echo $PATH
          echo ~
        shell: bash
      - name: Adjust $PATH (Windows only)
        run: |
          echo "~/.local/bin" >> $GITHUB_PATH
        shell: bash
        if: ${{ matrix.platform == 'windows-latest' }}
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Install nightly all
        run: |
          bash install.sh nightly all
          lfc --version
          lfd --version
          lff --version
        #   which epoch
        shell: bash
      - name: Install stable all
        run: |
          bash install.sh stable all
        # FIXME currently not working. Uncomment after releasing v0.5.0
        #   lfc --version
        #   lff --version
        shell: bash
      - name: Install epoch cli
        run: |
          bash install.sh epoch cli
        # FIXME currently not working. Uncomment after releasing v0.5.0
        #  lfc --version
        #  lff --version
        shell: bash
