name: CI

on:
  push:
  pull_request:

jobs:
  install:
    strategy:
        matrix:
          platform: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.platform }}  
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with:
          distribution: oracle
          java-version: 17
      - name: Print diagnostics
        run: |
          echo $PATH
        shell: bash
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Install nightly all
        run: |
          bash install.sh nightly all
          lfc --version
          lfd --version
          lff --version
        shell: bash
      - name: Install stable all
        run: |
          bash install.sh stable all
          lfc --version
          lff --version
        shell: bash
      - name: Install epoch cli
        run: |
          bash install.sh epoch cli
          lfc --version
          lff --version
        shell: bash
